version: '3'
volumes:
  assets:
services:
  postgres:
    image: postgres:9.6.2
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
