version: '3'
volumes:
  assets:
services:
  postgres:
    image: postgres:9.6.2
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - assets:/srv/public/assets
    environment:
      - SECRET_KEY_BASE
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - assets:/srv/public/assets
    ports:
      - 80:80
