default: &default
  adapter: postgresql
  host: localhost
  username: postgres

development:
  <<: *default
  database: spree_react_dev

test:
  <<: *default
  database: spree_react_test

production:
  <<: *default
  host: postgres
  database: spree_react
