default: &default
  adapter: postgresql
  host: localhost
  username: postgres

development:
  <<: *default
  database: spree_react_dev

test:
  <<: *default
  database: spree_react_test

build:
  adapter: sqlite3
  database: db/build.sqlite3

production:
  <<: *default
  host: postgres
  database: spree_react
